# Add 'repo' label to any root file changes
repo:
  - ./*

# Add 'test' label to any change to *.spec.js files within the source dir
docker:
  - any: [ 'DockerFile', 'docker/*' ]

GH:
- any: ['.github/*']
